# Generated by Django 4.2.2 on 2023-08-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='static/upload'),
        ),
    ]
